/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2020-04-14 09:40:09 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost/express -t books -s public
 *
 */


export namespace booksFields {
    export type id = number;
    export type title = string;
    export type author = string | null;

}

export interface books {
    id: booksFields.id;
    title: booksFields.title;
    author: booksFields.author;

}
