/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2020-04-14 13:58:15 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost/express -t book -s public
 *
 */


export namespace bookFields {
    export type id = number;
    export type title = string;
    export type author = string | null;

}

export interface book {
    id: bookFields.id;
    title: bookFields.title;
    author: bookFields.author;

}
